language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t aarontawat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aarontawat/docker-react npm run test

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-445023821325"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_acces_key: $AWS_SECRET_KEY
  
